### ISSUE TITLE
Quantitative Results of E-DSSR

### ISSUE THREAD

**Issue by Rashfu** [med-air/EndoNeRF#12]
Hi there,

I'm looking for the code for the E-DSSR algorithm, but I haven't been able to find it on GitHub. Could you point me in the right direction to access the code or let me know if it's not available publicly? Any help would be much appreciated.

Thank you!

**Comment by yuehaowang** [comment]
Hi, thanks for your question.

The complete code of E-DSSR is not released yet. But you can use its underlying reconstruction framework [SurfelWarp](https://github.com/weigao95/surfelwarp) and the depth estimator [STTR](https://github.com/mli0603/stereo-transformer) to reproduce its results.

**Comment by Rashfu** [comment]
Thank you for your answer！I'll give them a try.
