### ISSUE TITLE
I set use_fgmask = False，it get  local variable 'ray_importance_maps' referenced before assignment

### ISSUE THREAD

**Issue by sincerely1** [med-air/EndoNeRF#14]
hello,I want to train a NeRF without Mask, than I set use_fgmask=False,but it get " local variable 'ray_importance_maps' referenced before assignment" in run_endonerf.py at 1183 line. In the code, I found that load_llff_data function return mask none, so the  ray_importance_maps not be assigned. I don't know how to deal with it.

**Comment by yuehaowang** [comment]
Hi, thanks for your question.

Our provided code didn't implement for `use_fgmask=False` yet.
Nevertheless, you can disable tool mask-guided ray casting by creating *dummy masks*, i.e., full-black images.

**Comment by sincerely1** [comment]
ok，thank for you help.
