### ISSUE TITLE
手术工具部分光线采样

### ISSUE THREAD

**Issue by xwx0924** [med-air/EndoNeRF#16]
作者，您好，请问您一个问题：tissue部分在train的时候是正常发射光线，并在深度附近采样，那针对手术工具部分，在train的时候没有发射光线，后续在test恢复软组织的时候，该部分光线的采样点是随机采样的么~~

**Comment by yuehaowang** [comment]
Thanks for your question.

You are right. During testing/rendering, points are sampled using the same stratified sampling in the original NeRF.

**Comment by xwx0924** [comment]
好的，感谢及时回复~~
