### ISSUE TITLE
How do you get the bds in poses_bounds.npy?

### ISSUE THREAD

**Issue by yifliu3** [med-air/EndoNeRF#27]
Hi! Thanks for your great work. 

When reading the code, I find you use the bds in poses_bounds.npy to decide the near and far for each image, and may I know how you obtain these values? My guess is that you directly use the results of COLMAP, but you may do some other processes.

**Comment by yuehaowang** [comment]
It's okay to use the results of COLMAP.
In our data, the bds are computed based on the estimated depths:
```
near = np.percentile(depth, 3.)
far = np.percentile(depth, 99.)
```
