### ISSUE TITLE
Dataset Split for results reported in paper EndoNeRF

### ISSUE THREAD

**Issue by ysjue** [med-air/EndoNeRF#29]
Hi, I noticed you left the code for users to freely select frames for testing (run_endonerf.py: Line 772-773) and you set it to "use all frames for reconstruction" by default. Can I ask did you split your video clip into training and testing (i.e., novel and seen views in other NeRF papers) frames in your paper or did you just report the metrics based on all the frames? Thanks!

**Comment by yuehaowang** [comment]
For the results in the paper, I do not split training/testing views since I recognize this problem as a 3D reconstruction task and there is no novel viewpoint for evaluation.

**Comment by ysjue** [comment]
Thank you!
