### ISSUE TITLE
How to get metric depth from the STTR estimation result?

### ISSUE THREAD

**Issue by yifliu3** [med-air/EndoNeRF#30]
Dear devs,

Thanks a lot for open-sourcing the code! I noticed that you get metric depth values by using a stereo depth estimation model STTR-light. Yet I found that STTR-light can only give disp values, I guess to get depth values, more parameters for the binocular camera should be given like the baseline. If so, may I request these parameters for further study? 

Thanks a lot!

**Comment by MichaelWangGo** [comment]
Hi, 

Did you get the baseline parameter?

Thanks
