### ISSUE TITLE
nerf_type

### ISSUE THREAD

**Issue by xwx0924** [med-air/EndoNeRF#5]
Thanks for the code shared~~I have a question: about nerf_type parameter in the code。if I want to train a static multi view scene (RGB image and depth image with multiple views), can I directly select the nerf_type parameter type as original, use_depth parameter is true, so i can use depth supervision training the model.

**Comment by yuehaowang** [comment]
Yes, you can basically set `nerf_type = original`.

**Comment by xwx0924** [comment]
thank your!
