### ISSUE TITLE
demo中的重建结果

### ISSUE THREAD

**Issue by slam-nerf** [med-air/EndoNeRF#6]
您好！首先很高兴您能开源这么出色的成果。当我看到您的示例demo时，我发现重建的结果和输入的图像相比，发生了“扭曲”，像是几何结构发生了变化，请问您任务这是什么原因呢

**Comment by yuehaowang** [comment]
Thanks for your question but I am not sure about the "twists" (扭曲)  you referred to. Would you mind being more specific?

**Comment by slam-nerf** [comment]
> Thanks for your question but I am not sure about the "twists" (扭曲) you referred to. Would you mind being more specific?
![1664976841415](https://user-images.githubusercontent.com/113759814/194073920-523729ea-0f7d-47bc-98d8-b1738c1cf42a.png)
比如这张图像中，重建得到的图像看着比较“皱”，像是一团揉过的纸，而原图看着就比较平整和整齐
