### ISSUE TITLE
dataset is available?

### ISSUE THREAD

**Issue by chensjtu** [med-air/EndoNeRF#9]
I have applied the dataset for two weeks, do guys get the link?

**Comment by yuehaowang** [comment]
Sorry for my late response. I've sent the dataset link via email.

**Comment by chensjtu** [comment]
The sample dataset is avail! Thanks~

**Comment by windygoo** [comment]
> Sorry for my late response. I've sent the dataset link via email.

Could you send me the dataset link? I have sent the request email.

**Comment by yuehaowang** [comment]
> > Sorry for my late response. I've sent the dataset link via email.
> 
> Could you send me the dataset link? I have sent the request email.

You may directly email me if you need the sample dataset.
